export { default as DashboardTab }   from './DashboardTab.jsx';export { default as TaskaTab } from './TaskaTab.jsx';export { default as IndicatorsTab }  from './IndicatorsTab.jsx';
export { default as ChartsTab }      from './ChartsTab.jsx';
export { default as MissingTab }     from './MissingTab.jsx';
export { default as CompletenessTab }from './CompletenessTab.jsx';
export { default as NumericalTab }   from './NumericalTab.jsx';
export { default as CategoricalTab } from './CategoricalTab.jsx';
export { default as BmiTab }         from './BmiTab.jsx';
export { default as ZscoreTab }      from './ZscoreTab.jsx';
export { default as IcTab }          from './IcTab.jsx';
export { default as SpellingTab }    from './SpellingTab.jsx';
export { default as DupTab }         from './DupTab.jsx';
export { default as AgeTab }         from './AgeTab.jsx';
export { default as ChangesTab }     from './ChangesTab.jsx';
export { default as ProfileTab }     from './ProfileTab.jsx';
export { default as TableauPrepTab } from './TableauPrepTab.jsx';
export { default as MyvassDashboardTab } from './MyvassDashboardTab.jsx';
export { default as MyvassQualityTab } from './MyvassQualityTab.jsx';
export { default as KKMQualityTab } from './KKMQualityTab.jsx';
export { default as KKMVisualizationTab } from './KKMVisualizationTab.jsx';
export { default as KKMDuplicatesTab } from './KKMDuplicatesTab.jsx';
